### ISSUE TITLE
Bug for tight container

### ISSUE THREAD

**Issue by pocman** [mushishi78/box_packer#4]
Hi, 

I don't understand why Boxpacker is not able to pack those items into the container.

```
require 'box_packer'

BoxPacker.container [12, 10, 10], packings_limit: 1 do
  add_item [6,6,6]
  add_item [10,10,6]
  pack!

  puts packed_successfully           # false
end
```

It's working with [12, 12, 12] container.

**Comment by mushishi78** [comment]
Hey @pocman, general speaking [bin packing is an NP-hard problem](https://en.wikipedia.org/wiki/Bin_packing_problem). This solution is just first fit heuristic, which means that it finds relatively good solution fairly quickly but not necessarily the most optimal solution. I haven't gone through your specific example, but I imagine that it just fails to pack into 1 container for this example, rather than there being a bug as such. However, if you investigate and find that the algorithms doing something wrong specifically, I'm totally willing for that assumption to be proved wrong.

I wrote this quite a while ago and I've been meaning to go back and make the code a lot simpler so that it's for people to follow and understand what they can expect from this. Though maybe I should just add a paragraph to the readme explaining this.
